In [10]:
import pandas as pd
import datetime
import functions as f

In [11]:
#DF Cleaning and formatting

url = '../data/raw/universal_top_spotify_songs.csv'
df = pd.read_csv(url)

country_mapping = {
    'ZA': {'name': 'South Africa', 'continent': 'Africa'},
    'VN': {'name': 'Vietnam', 'continent': 'Asia'},
    'VE': {'name': 'Venezuela', 'continent': 'South America'},
    'UY': {'name': 'Uruguay', 'continent': 'South America'},
    'US': {'name': 'United States', 'continent': 'North America'},
    'UA': {'name': 'Ukraine', 'continent': 'Europe'},
    'TW': {'name': 'Taiwan', 'continent': 'Asia'},
    'TR': {'name': 'Turkey', 'continent': 'Europe/Asia'},
    'TH': {'name': 'Thailand', 'continent': 'Asia'},
    'SV': {'name': 'El Salvador', 'continent': 'North America'},
    'SK': {'name': 'Slovakia', 'continent': 'Europe'},
    'SG': {'name': 'Singapore', 'continent': 'Asia'},
    'SE': {'name': 'Sweden', 'continent': 'Europe'},
    'SA': {'name': 'Saudi Arabia', 'continent': 'Asia'},
    'RO': {'name': 'Romania', 'continent': 'Europe'},
    'PY': {'name': 'Paraguay', 'continent': 'South America'},
    'PT': {'name': 'Portugal', 'continent': 'Europe'},
    'PL': {'name': 'Poland', 'continent': 'Europe'},
    'PK': {'name': 'Pakistan', 'continent': 'Asia'},
    'PH': {'name': 'Philippines', 'continent': 'Asia'},
    'PE': {'name': 'Peru', 'continent': 'South America'},
    'PA': {'name': 'Panama', 'continent': 'North America'},
    'NZ': {'name': 'New Zealand', 'continent': 'Oceania'},
    'NO': {'name': 'Norway', 'continent': 'Europe'},
    'NL': {'name': 'Netherlands', 'continent': 'Europe'},
    'NI': {'name': 'Nicaragua', 'continent': 'North America'},
    'NG': {'name': 'Nigeria', 'continent': 'Africa'},
    'MY': {'name': 'Malaysia', 'continent': 'Asia'},
    'MX': {'name': 'Mexico', 'continent': 'North America'},
    'MA': {'name': 'Morocco', 'continent': 'Africa'},
    'LV': {'name': 'Latvia', 'continent': 'Europe'},
    'LU': {'name': 'Luxembourg', 'continent': 'Europe'},
    'LT': {'name': 'Lithuania', 'continent': 'Europe'},
    'KZ': {'name': 'Kazakhstan', 'continent': 'Asia'},
    'KR': {'name': 'South Korea', 'continent': 'Asia'},
    'JP': {'name': 'Japan', 'continent': 'Asia'},
    'IT': {'name': 'Italy', 'continent': 'Europe'},
    'IS': {'name': 'Iceland', 'continent': 'Europe'},
    'IN': {'name': 'India', 'continent': 'Asia'},
    'IL': {'name': 'Israel', 'continent': 'Asia'},
    'IE': {'name': 'Ireland', 'continent': 'Europe'},
    'ID': {'name': 'Indonesia', 'continent': 'Asia'},
    'HU': {'name': 'Hungary', 'continent': 'Europe'},
    'HN': {'name': 'Honduras', 'continent': 'North America'},
    'HK': {'name': 'Hong Kong', 'continent': 'Asia'},
    'GT': {'name': 'Guatemala', 'continent': 'North America'},
    'GR': {'name': 'Greece', 'continent': 'Europe'},
    'FR': {'name': 'France', 'continent': 'Europe'},
    'FI': {'name': 'Finland', 'continent': 'Europe'},
    'ES': {'name': 'Spain', 'continent': 'Europe'},
    'EG': {'name': 'Egypt', 'continent': 'Africa'},
    'EE': {'name': 'Estonia', 'continent': 'Europe'},
    'EC': {'name': 'Ecuador', 'continent': 'South America'},
    'DO': {'name': 'Dominican Republic', 'continent': 'North America'},
    'DK': {'name': 'Denmark', 'continent': 'Europe'},
    'DE': {'name': 'Germany', 'continent': 'Europe'},
    'CZ': {'name': 'Czech Republic', 'continent': 'Europe'},
    'CR': {'name': 'Costa Rica', 'continent': 'North America'},
    'CO': {'name': 'Colombia', 'continent': 'South America'},
    'CL': {'name': 'Chile', 'continent': 'South America'},
    'CH': {'name': 'Switzerland', 'continent': 'Europe'},
    'CA': {'name': 'Canada', 'continent': 'North America'},
    'BY': {'name': 'Belarus', 'continent': 'Europe'},
    'BR': {'name': 'Brazil', 'continent': 'South America'},
    'BO': {'name': 'Bolivia', 'continent': 'South America'},
    'BG': {'name': 'Bulgaria', 'continent': 'Europe'},
    'BE': {'name': 'Belgium', 'continent': 'Europe'},
    'AU': {'name': 'Australia', 'continent': 'Oceania'},
    'AT': {'name': 'Austria', 'continent': 'Europe'},
    'AR': {'name': 'Argentina', 'continent': 'South America'},
    'AE': {'name': 'United Arab Emirates', 'continent': 'Asia'},
    'GB': {'name': 'United Kingdom', 'continent': 'Europe'}
}

#Make columns lower case for readibility.
df.rename(columns={ col: col.rstrip().replace(" ", "_").lower() for col in df.columns}, inplace=True)

#Dropping null values
df = df.dropna(subset=['country','artists'])

#converting date column to date.
df['snapshot_date'] = pd.to_datetime(df['snapshot_date'])
df['month'] = df['snapshot_date'].apply(lambda x: x.month if isinstance(x, pd.Timestamp) else x)
df['year'] = df['snapshot_date'].apply(lambda x: x.year if isinstance(x, pd.Timestamp) else x)

#Data from the last 3 months.
df = df[df['snapshot_date'] >= '2024-09-01']

#Top 20 ranked
df = df[df['daily_rank'] <= 20]

#added columns for full country name and continent
df["country_full"] = df["country"].map(lambda x: country_mapping.get(x, {}).get('name', 'Unknown'))
df["continent"] = df["country"].map(lambda x: country_mapping.get(x, {}).get('continent', 'Unknown'))

#dropped irrelevant columns
df = df[['spotify_id','name','artists','daily_rank','daily_movement','weekly_movement','snapshot_date','popularity','is_explicit','album_name','album_release_date','danceability','energy','loudness','month','year','country_full','continent']]

#renamed column country
df.rename(columns={'country_full':'country'},inplace=True)

#filtered out by continent
df = df[df['continent'] == 'Europe']

In [12]:
#DF Cleaning and formatting

url2 = '../data/raw/music_festivals.csv'
df2 = pd.read_csv(url2)

#Make columns lower case for readibility.
df2.rename(columns={ col: col.rstrip().replace(" ", "_").lower() for col in df2.columns}, inplace=True)

# Extracting the first character as currency symbol
df2['currency'] = df2['economic_impact'].astype(str).str.strip().str[0]

# Cleaning economic_impact column with a lambda function
df2['economic_impact'] = df2['economic_impact'].astype(str).apply(
    lambda x: float(x.lstrip("£€").strip().replace("million", "").strip()) * 1_000_000
    if any(sym in x for sym in ["£", "€"]) else None
)


# Filtering for specific currencies
df2 = df2[df2['currency'].isin(['£', '€'])]

# Rename the column 'location' to 'attendance'
df2.rename(columns={'location': 'attendance','festival_name':'country','attendance_numbers':'age_group','music_genre':'genre'}, inplace=True)

#making attendance and economic_impact numeric values.
df2['attendance'] = df2['attendance'].astype(float)
df2['economic_impact'] = df2['economic_impact'].astype(float)

#countries with the most economic impact
pivot_table = df2.pivot_table(index='country',values='economic_impact').sort_values(by='economic_impact',ascending=False)
pivot_table = pivot_table['economic_impact'].apply(lambda x: f"{x:,.2f}")

#clean festival_name values
df2['country'] = df2['country'].apply(lambda x: x.strip())

#assigned festivalID to table.
df2 = df2.reset_index()
df2.rename(columns={'index':'festival_id'},inplace=True)

#drop irrelevant columns
df2.drop(columns={'unnamed:_0'},inplace=True)

#replace 'UK' for 'United Kingdom'
df2['country'] = df2['country'].replace('UK','United Kingdom')

In [13]:
#ID generator
f.generate_id(df,['album_name'],'album_id')
f.generate_id(df2,['age_group','visitor_demographics'],'demographic_id')
f.generate_id(df2,['genre'],'genre_id')
f.generate_id(df2,['country','currency'],'country_id')
f.generate_id(df,['country'],'country_id')
f.generate_id(df2,['genre'],'genre_id')

,festival_id,country,attendance,age_group,visitor_demographics,economic_impact,genre,currency,demographic_id,genre_id,country_id
0,0,United Kingdom,200000.0,18-35,Music Enthusiasts,100000000.0,Various,£,1,1,1
1,1,Belgium,400000.0,18-30,EDM Fans,150000000.0,EDM,€,2,2,2
2,2,Hungary,500000.0,18-40,International Attendees,130000000.0,Various,€,3,1,3
3,3,Germany,90000.0,20-40,Rock Fans,80000000.0,Rock,€,4,3,4
4,5,United Kingdom,100000.0,16-35,Rock and Indie Fans,60000000.0,Rock/Indie,£,5,4,1
...,...,...,...,...,...,...,...,...,...,...,...
74,138,Montenegro,10000.0,18-40,Rock and Jazz Fans,5000000.0,Rock/Jazz,€,62,39,13
75,167,Andorra,8000.0,18-35,Rock and Electronic Fans,4000000.0,Rock/Electronic,€,13,11,28
76,168,San Marino,10000.0,18-35,Pop and Jazz Fans,5000000.0,Pop/Jazz,€,63,43,29
77,170,Monaco,12000.0,18-40,Jazz and Electronic Fans,6000000.0,Jazz/Electronic,€,64,44,30
78,171,Vatican City,5000.0,18-60,Classical and Choral Fans,2000000.0,Classical/Choral,€,65,45,31

In [31]:
#DataFrame creations for table exporting

#Generating song table
song_df = df[['spotify_id', 'name', 'is_explicit','artists','album_id']].drop_duplicates()
song_df['is_explicit'] = song_df['is_explicit'].replace({'False': 0, 'True': 1})

#Generating songs_features table
songs_features_df = df[['spotify_id','danceability','energy','loudness']].drop_duplicates()

#Generating album table
album_df = df[['album_id','album_name','album_release_date']].drop_duplicates()

#Generating rankings table
rankings_df = df[['spotify_id','snapshot_date','country_id','daily_rank','daily_movement','weekly_movement','popularity']].drop_duplicates()

#Generating genre table
genre_df = df2[['genre_id','genre']].drop_duplicates()

#generating demographics table
demographics_df = df2[['demographic_id','age_group','visitor_demographics']].drop_duplicates()


#generating region table
region_df = df2[['country_id','country','currency']].drop_duplicates()
country_id_mapping = region_df[['country_id', 'country']].drop_duplicates().set_index('country')['country_id'].to_dict()
df['country_id'] = df['country'].map(country_id_mapping)
df2['country_id'] = df2['country'].map(country_id_mapping)

#generating festivals_genres table
festivals_genres_df = df2[['festival_id','genre_id']].drop_duplicates()

#generating music_festivals table
music_festivals_df = df2[['festival_id','demographic_id','country_id','attendance','economic_impact','genre_id']].drop_duplicates()

In [33]:
#Create csv
f.save_to_csv(song_df, 'songs_df.csv')
f.save_to_csv(songs_features_df, 'songs_features_df.csv')
f.save_to_csv(album_df, 'album_df.csv')
f.save_to_csv(rankings_df, 'rankings_df.csv')
f.save_to_csv(genre_df, 'genre_df.csv')
f.save_to_csv(demographics_df, 'demographics_df.csv')
f.save_to_csv(region_df, 'region_df.csv')
f.save_to_csv(festivals_genres_df, 'festivals_genres_df.csv')
f.save_to_csv(music_festivals_df, 'music_festivals_df.csv')

DataFrame successfully saved to ../data/clean/songs_df.csv
DataFrame successfully saved to ../data/clean/songs_features_df.csv
DataFrame successfully saved to ../data/clean/album_df.csv
DataFrame successfully saved to ../data/clean/rankings_df.csv
DataFrame successfully saved to ../data/clean/genre_df.csv
DataFrame successfully saved to ../data/clean/demographics_df.csv
DataFrame successfully saved to ../data/clean/region_df.csv
DataFrame successfully saved to ../data/clean/festivals_genres_df.csv
DataFrame successfully saved to ../data/clean/music_festivals_df.csv